name = "AlgebraicMeshes"
uuid = "6f309771-d163-45c3-98c4-9f437ea4a81a"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.0.1"

[deps]
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
AlgebraicMeshesMakieExt = "Makie"

[compat]
DomainSets = "0.6"
Makie = "0.19"
StaticArrays = "1"

[extras]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Makie", "Test"]
